### ISSUE TITLE
More detailed examples

### ISSUE THREAD

**Issue by sergiomeneses** [zakarumych/alkahest#10]
Hi, i'm tryng to use this library for deserialize the response of a quake 3 engine game server, right now i send the UDP query to the server and get the bytes response which i can convert with `Sring::from_utf8_lossy`  to get a string and iterate over it to get players, server variables and server info (using `split`, 'collect', etc..).

I want to this lib instance but i can't the guideness on how to proced, can your give me an advise about this, thanks

**Comment by zakarumych** [comment]
Alkahest has its own binary format designed to support lazy parsing and zero-overhead serialization.

You need to parse existing format, so it is not entirely possible/easy to do with Alkahest.

Imo your best bet is 'nom' crate that is designed specifically to construct parsers of any existing format.

**Comment by sergiomeneses** [comment]
Thanks, btw great work, congratulations.
