### ISSUE TITLE
Cannot implement serialization traits by hand without reaching into private module

### ISSUE THREAD

**Issue by vlovich** [zakarumych/alkahest#15]
Namely Buffer and Sizes I think are the two types that need to be reexported at the crate level?

**Comment by zakarumych** [comment]
Would [this](https://docs.rs/alkahest/0.3.0/alkahest/advanced/index.html) help?

**Comment by vlovich** [comment]
Oh I hadn't realized that's where it was exposed. Thanks for the pointer.
